### ISSUE TITLE
Uvoz

### ISSUE THREAD

**Issue by marijajaneva** [marijajaneva/APPR-2020-21#1]
Prosila bi, če mi lahko pregledate kodo za uvoz, če je vredu oz. kaj moram še dodat. Želela sem dodati encoding Windows-1250, vendar mi je javlo napako.

**Comment by katarinabrilej** [comment]
Uvoz knjižnic v datoteki `uvoz.r` raje premakni v datoteko `libraries.r` v mapi `lib`, da se knjižnice v nadaljevanju ne bodo ponavljale. 

Imena csv datotek dopolni s podčrtaji, da ne bo presledkov (trenutno je nekaj podčrtajev in nekaj presledkov). Tabelo
`selitve_po_regijah` lahko nato uvoziš na naslednji način
```
selitve_po_regijah <- read.csv("podatki/selitve_po_regijah.csv", skip = 2,
                               header = TRUE, na.string = "-",
                               fileEncoding = "Windows-1250", encoding = "UT-8")
```
Tabelo je potrebno spremeniti v obliko tidy data, da bodo tabelo sestavljali trije stolpci, ki bodo vsebovali naslednje podatke
* regija odselitve
* leto
* regija priselitve
Če boš pri urejanju tabele potrebovala pomoč, napiši.

Tudi tabelo `selitve_po_starostnih_skupinah` je potrebno preoblikovati v obliko tidy data:
```
selitve_po_starostnih_skupinah <- read.csv("podatki/selitve_po_starostnih_skupinah.csv",
                                           header = TRUE, skip = 2)
colnames(selitve_po_starostnih_skupinah) <- c("starostna_skupina", 2000:2020)
selitve_po_starostnih_skupinah <- selitve_po_starostnih_skupinah %>% pivot_longer(-1, 
                                  names_to="leto", values_to="stevilo_selitev")
```
V stolpcu starostna_skupina se lahko besede let znebiš s pomočjo regularnih izrazov. 

Tabelo `stanovanjske_razmere` uvoziš na podoben način kot prvo tabelo:
```
stanovanjske_razmere <- read.csv("podatki/stanovanjske_razmere.csv",
                                 skip = 2, header = TRUE,
                                 fileEncoding = "Windows-1250", encoding = "UT-8")
```
Tudi tu je potrebno preoblikovati v obliko tidy data, tabela mora imeti tri stolpce:
statistična regija, leto in kakovost stanovanja.

Enako velja za tabelo `stanovanjski_stroski`.

**Comment by marijajaneva** [comment]
A bi mi lahko prosim pomagala še preoblikovanju prve tabele v obliko tidy data, ker je več stolpcev in mi ne uspe oblikovat v željeno tabelo.

**Comment by katarinabrilej** [comment]
Tabelo peoblikuješ na naslednji način:

```
selitve_po_regijah <- selitve_po_regijah%>%
  pivot_longer(cols = -1, 
               names_to = c('leto', 'regija_priselitve'), 
               names_sep = "\\.v\\.")
```
Nato je potrebno urediti še letnice (brez X) in imena regij, tako za priselitev in odselitev. Npr. Pomurska in ne iz Pomurske in Pomursko.
