### ISSUE TITLE
Vizualizacija

### ISSUE THREAD

**Issue by marijajaneva** [marijajaneva/APPR-2020-21#2]
Prosim za pomoč pri risanju grafov. 
Rada bi narisala graf, za prvo tabelo, posebej graf za priselitve in posebej za odselitve, in bi imela par premic v istem grafu za različna leta, če se da. Potrebovala bi pomoč pri sestavljanju funkcije za risanje takega grafa.

**Comment by katarinabrilej** [comment]
Ne predstavljam si točno kakšen graf želiš narisati. Torej kaj bi bilo na osi x in kaj na osi y?

**Comment by marijajaneva** [comment]
1. Na osi x bi imela regije_odselitve, na osi y bi imela stevilo_ preseljencev . Potem  bi pa rada naredila filter, da pokaže samo za določeno leto, oz če se da več premic v grafu za več leta, da se malo primerja. 

Probala sem nekako narisat, vendar mi ne prime filter, mogoče če bi lahko še pogledala če je uvoz vredu narejen. 

2. Pri drugem grafu pa sem narisala, venar mi pa ne prime geom_line(), da bi povezala pike.

**Comment by katarinabrilej** [comment]
Graf, ki ga želiš lahko narišeš z naslednjo kodo
```
izseljeni <- selitve_po_regijah %>% group_by(regija_odselitve,leto) %>% 
  summarize(izseljeni_sum = sum(stevilo_preseljencev))
ggplot(izseljeni, aes(regija_odselitve, izseljeni_sum)) + 
  geom_line(aes(group = leto, colour = factor(leto)))
```
Vendar se mi zdi bolj smiselno, če bi  bilo na x osi leto in bi prikazala kako se je spreminjalo število izseljencev skozi leta po pokrajinah ali pa če bi za neko leto narisala število izseljencev za vse pokrajine, recimo s stolpičnim diagramom.
Recimo nekaj od naslednjega
```
ggplot(izseljeni, aes(leto, izseljeni_sum)) + 
  geom_line(aes(group = regija_odselitve, colour = factor(regija_odselitve)))
```
ali pa
```
leto2000 <- izseljeni[izseljeni$leto == " 2000",c(1,3)]
ggplot(leto2000, aes(regija_odselitve,izseljeni_sum)) +
geom_col()
```
Seveda je potrebno grafe še urediti.

**Comment by katarinabrilej** [comment]
Opozorila bi še, da imaš v tabeli `selitve_po_regijah` v stolpcu `leto` pred številom presledek, tega bi bilo potrebno umakniti. 

Drugi graf narišeš na naslednji način, torej znotraj `geom_line` je potrebno dodati `group = 1`
```
ggplot(selitve_po_starostnih_skupinah %>%filter(leto=="2000"), 
       aes(starostna_skupina, stevilo_selitev)) + geom_point() + geom_line(group = 1) 
```
